import esbuild from 'esbuild';
import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import process from 'process';
import builtins from 'builtin-modules';

function applyVersion() {
  const shortSha = execSync('git rev-parse --short HEAD').toString().trim();
  const tagAtHead = execSync('git tag --points-at HEAD').toString().trim();

  let version;
  if (tagAtHead) {
    version = tagAtHead.split('\n')[0].replace(/^v/, '');
  } else {
    const latestTag = execSync('git describe --tags --abbrev=0').toString().trim().replace(/^v/, '');
    version = `${latestTag}-next-${shortSha}`;
  }

  const manifestPath = 'dist/manifest.json';
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  manifest.version = version;
  manifest.main = 'main.js';
  writeFileSync(manifestPath, JSON.stringify(manifest, null, '\t') + '\n');

  console.log(`dist/manifest.json version set to ${version}`);
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  minify: prod ? true : false,
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
});

if (prod) {
  await context.rebuild();
  cpSync('manifest.json', 'dist/manifest.json');
  cpSync('styles.css', 'dist/styles.css');
  applyVersion();
  process.exit(0);
} else {
  mkdirSync('dist', { recursive: true });
  cpSync('manifest.json', 'dist/manifest.json');
  cpSync('styles.css', 'dist/styles.css');
  applyVersion();
  await context.watch();
}
